services:
  - type: web
    name: laravel-apache-app
    repo: https://github.com/AdrianOrdonez2705/UrbanLifeBackend.git
    autoDeploy: true
    runtime: docker
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: ${RENDER_EXTERNAL_URL}
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: db.jflzvvhmzjuqbmfuzxvi.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: APP_KEY
        secret: true
      - key: DB_PASSWORD
        secret: true